# Generated by Django 5.0.5 on 2024-05-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_courseoutcome_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseoutcome',
            old_name='u_ap',
            new_name='uap',
        ),
    ]
