# Generated by Django 5.0.6 on 2024-05-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_courecontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoureContent',
            new_name='CourseContent',
        ),
    ]
