# Generated by Django 5.0.6 on 2024-05-17 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_courecontent_coursecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oref', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tb', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='WebReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr', to='api.subject')),
            ],
        ),
    ]
