# Generated by Django 5.0.6 on 2024-05-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_onlinereference_referencebook_textbook_webreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencebook',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
