# Generated by Django 5.0.6 on 2024-05-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subject_t_or_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='t_or_p',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Theory and Pratical', 'Theory and Practical')], default='Theory', max_length=50),
        ),
    ]
