# Generated by Django 5.0.6 on 2024-05-20 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_subject_t_or_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='t_or_p',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Theory and Practical', 'Theory and Practical')], default='Theory', max_length=50),
        ),
        migrations.CreateModel(
            name='CourseObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cob', to='api.subject')),
            ],
        ),
    ]
