# Generated by Django 5.0.6 on 2024-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_subject_t_or_p_courseobjectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutcome',
            name='uap',
            field=models.CharField(choices=[('U', 'U'), ('AP', 'AP'), ('AN', 'AN')], max_length=100),
        ),
    ]
