# Generated by Django 5.0.6 on 2024-05-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_courseoutcome_uap'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=100)),
                ('lie', models.CharField(max_length=400)),
                ('co_mappping', models.CharField(max_length=100)),
                ('rbt', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='api.subject')),
            ],
        ),
    ]
