# Generated by Django 5.0.6 on 2024-05-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_labcomponent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labcomponent',
            old_name='co_mappping',
            new_name='co_mapping',
        ),
    ]
