# Generated by Django 5.0.6 on 2024-05-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_courseobjectives_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutcome',
            name='title',
        ),
    ]
