# Generated by Django 5.0.6 on 2024-05-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_courseoutcome_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labcomponent',
            name='sno',
        ),
    ]
