# Generated by Django 5.0.6 on 2024-05-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_labcomponent_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='sno',
        ),
    ]
