# Generated by Django 5.0.6 on 2024-05-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_textbook_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencebook',
            name='sno',
        ),
    ]
