# Generated by Django 5.0.6 on 2024-05-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_referencebook_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webreference',
            name='sno',
        ),
    ]
