# Generated by Django 5.0.6 on 2024-05-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_webreference_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='module',
        ),
        migrations.RemoveField(
            model_name='onlinereference',
            name='sno',
        ),
    ]
