# Generated by Django 5.0.6 on 2024-05-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_coursecontent_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutcome',
            name='title',
            field=models.CharField(default='CO', max_length=200),
        ),
    ]
