# Generated by Django 5.0.6 on 2024-05-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_courseoutcome_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutcome',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
