# Generated by Django 5.0.6 on 2024-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_courseoutcome_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutcome',
            name='uap',
            field=models.CharField(choices=[('Understanding', 'U'), ('Applying', 'AP'), ('Analyzing', 'AN'), ('Remembering', 'R'), ('Creating', 'C'), ('Evaluating', 'E')], max_length=100),
        ),
    ]
