# Generated by Django 5.0.6 on 2024-05-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_courseoutcome_uap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutcome',
            name='uap',
            field=models.CharField(choices=[('U', 'Understanding'), ('AP', 'Applying'), ('AN', 'Analyzing'), ('R', 'Remembering'), ('C', 'Creating'), ('E', 'Evaluating')], max_length=100),
        ),
    ]
