# Generated by Django 5.0.6 on 2024-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_course_tuition_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutcome',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
